import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/navbar'
import Dashboard from '@/components/home/home'
import Leaderboard from '@/components/leaderboard/leaderboard'
import Card from '@/components/card/card'
import AuctionScreen from './auction/auction_screen'
import BidTable from './auction/BidTable'
import Squad from './auction/Squad'
import SignupForm from './signup/signup'
import Login from './login/login'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>FantasyBids</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* <AuctionScreen /> */}
      {/* <Dashboard /> */}
      {/* <SignupForm /> */}
      <Card />
      <AuctionScreen />
      {/* <Login /> */}
      {/* <Squad /> */}
      {/* <Leaderboard /> */}
    </>
  )
}
